### ISSUE TITLE
fillText() in Docker and fatal runtime error: Rust cannot catch foreign exceptions

### ISSUE THREAD

**Issue by andrey-hohlov** [samizdatco/skia-canvas#17]
Hi,

Trying to run it in Docker:

```
FROM node:14-alpine

# Fix Error: Error loading shared library libfontconfig.so.1: No such file or directory (needed by /node_modules/skia-canvas/lib/v6/index.node)
RUN apk add fontconfig

# Fix Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /node_modules/skia-canvas/lib/v6/index.node)
RUN apk add libc6-compat
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force
RUN mkdir /opt/app && chown node:node /opt/app
WORKDIR /opt/app
USER node
COPY . ./
CMD ["node", "index.js"]
```

It basically works (using code from readme), but ``fillText()``` or ```measureText()``` call throws error:

```
fatal runtime error: Rust cannot catch foreign exceptions
```

I suppose it can be a problem with some system dependencies.
I tried Ubuntu in Docker and it works:

```
FROM ubuntu

RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install sudo
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

# Fix  Error: Error loading shared library libfontconfig.so.1: No such file or directory (needed by /node_modules/skia-canvas/lib/v6/index.node)
RUN apt-get -y install fontconfig

COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force
RUN mkdir /opt/app
WORKDIR /opt/app
COPY . ./
CMD ["node", "index.js"]
```

Any ideas?

**Comment by samizdatco** [comment]
I suspect the problem running on Alpine is related to the underlying bindings having been compiled for GNU libc (see rust-skia/rust-skia#356) and your symlink in the musl libc seems to be giving it indigestion. The discussion over there makes it sound like building the rust components from source is possible (with some modifications to support musl), so maybe it would make sense to generate binaries for `skia-canvas` that are libc-specific.

If you feel like experimenting, I'd be very curious to see how an `npm run build && npm test` within the module repo would go on Alpine...

**Comment by andrey-hohlov** [comment]
Hi, @samizdatco 

I searched a lot and also found that issue. But I'm pretty far from Rust and not a strong Docker user.

Anyway, I tried to build ```skia-canvas``` in the Docker container.
Just run it and then played inside using Google to find solutions:

```
docker run -it node:14-alpine /bin/ash
```

```
apk add --no-cache curl

curl https://sh.rustup.rs -sSf | sh
apk add --no-cache build-base python fontconfig
export PATH=$PATH:~/.cargo/bin

curl -L -O https://github.com/samizdatco/skia-canvas/archive/refs/heads/master.zip
unzip master.zip
cd skia-canvas-master
npm install
npm run build
```

```
error: cannot produce cdylib for `skia-canvas v0.9.21 (/skia-canvas-master)` as the target `x86_64-unknown-linux-musl` does not support these crate types
Did not copy "cdylib:skia-canvas"
```

I used the ```cargo c``` command. It took a lot of time and everything was green, but

```
error: failed to run custom build command for `skia-bindings v0.39.1`

Caused by:
  process didn't exit successfully: `/skia-canvas-master/target/debug/build/skia-bindings-ec7415cd6d37c99c/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.39.1/750688025ba50471efe8-x86_64-unknown-linux-musl-textlayout-static
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.39.1/skia-binaries-750688025ba50471efe8-x86_64-unknown-linux-musl-textlayout-static.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.39.1/skia-binaries-750688025ba50471efe8-x86_64-unknown-linux-musl-textlayout-static.tar.gz: status code 404
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 2 found: "python"
  Synchronizing Skia dependencies
  DOWNLOADING: https://codeload.github.com/rust-skia/skia/tar.gz/m90-0.38.3
  DOWNLOADING: https://codeload.github.com/rust-skia/depot_tools/tar.gz/a110bf6

  --- stderr
  Traceback (most recent call last):
    File "skia/tools/git-sync-deps", line 266, in <module>
      exit(main(sys.argv[1:]))
    File "skia/tools/git-sync-deps", line 258, in main
      git_sync_deps(deps_file_path, argv, verbose)
    File "skia/tools/git-sync-deps", line 198, in git_sync_deps
      assert git
  AssertionError
  thread 'main' panicked at '`skia/tools/git-sync-deps` failed', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.39.1/build_support/skia.rs:630:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Found issues like https://github.com/rust-lang/cargo/issues/7154 and https://github.com/rust-lang/rust/issues/59302

If I change ```crate-type``` in ```Cargo.toml``` to ```staticlib``` (just for test, I'm not sure I understand how it works) - build process works until the same error with not found ```unknown-linux-musl-textlayout-static``` binaries.


I need to run the app asap and it looks like```skia-canvas``` solves all problems I have with another drawing library.
On ```node:14-slim``` and ```node:14```  I got the error:

```
/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27" not found
```

I suppose I have to compile lib in that environment to solve it. Quickly tried, it compiles and passes tests. So multi-stage build can be used. But I don't stick with the node version, so this Dockerfile works for me:

```
FROM node:16-slim
RUN apt-get update
RUN apt install -y libfontconfig1
# other standard node.js app stuff
```

Sorry for too much verbose explanation, maybe it will be helpful for somebody else.


I'll be happy to try something more to run it on alpine if you have ideas.

**Comment by samizdatco** [comment]
Version 0.9.27 adds support for Alpine containers (though you do still need to run `apk add fontconfig` to get things working).
