### ISSUE TITLE
Not working in serverless environments (e.g. AWS Lambda)

### ISSUE THREAD

**Issue by seveibar** [samizdatco/skia-canvas#2]
I get the following error when running in a serverless environement. Is there any way to bundle the required shared library with this module? If not, how would one go about using this library in a serverless environment (in my case, vercel)

```
ERROR	Error: libfontconfig.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/task/node_modules/skia-canvas/lib/classes.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
RequestId: 5b8f75f9-1076-428d-b606-aee16d5ed020 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by samizdatco** [comment]
It looks like you'll need to install some dependencies (apparently including FontConfig but I'd be curious to hear if you find you're missing anything else). It looks like this is a common enough pitfall with Lambda that there's an article about installing it here:
https://medium.com/creditorwatch/aws-lambda-fonts-libfontconfig-5e837281a4ce

And here's a more concise recipe:
https://gist.github.com/nat-n/c3429d29f2478ccb3de243810bb12956

**Comment by alexandr2110pro** [comment]
It would be nice if you added the documentation section about that.

**Comment by Autometrique** [comment]
@samizdatco 
Hi!
I can't install skia-canvas on Vercel (serverless) either. I'm not sure how to fix this error.

Here is the log:


Failed to compile.
--
./node_modules/skia-canvas/lib/index.js
Module not found: Can't resolve './v6'

**Comment by juaoose** [comment]
Has anyone managed to use this on aws lambda? Used layers? Custom runtime? Thanks.

**Comment by samizdatco** [comment]
Layers for use with AWS Lambda will be available starting with the 2.1 release. See the readme for [instructions on using them](https://github.com/samizdatco/skia-canvas/?tab=readme-ov-file#running-on-aws-lambda).
