### ISSUE TITLE
Unsupported syntax when using Node v12.18.3

### ISSUE THREAD

**Issue by thers** [samizdatco/skia-canvas#28]
With Node v12.18.3 (which is listed as supported as 12.17+).

```
C:\dev\test\node-tests\node_modules\skia-canvas\lib\index.js:27
        slot[getset ?? attr] = fn
                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\dev\test\node-tests\index.js:2:29)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by basicer** [comment]
@samizdatco Could you please cut an npm release that includes this fix?

**Comment by samizdatco** [comment]
Good idea! Thanks for the reminder.
